### ISSUE TITLE
expectation

### ISSUE THREAD

**Issue by af-doom** [hku-mars/joint-lidar-camera-calib#1]

**Comment by af-doom** [comment]
> Thanks for your interest in our work! I just uploaded the codes. The data will be released soon.
Hello, thank you very much for your open source code. I just looked at the data. Does this only support solid-state LiDAR

**Comment by af-doom** [comment]
> Thanks for your interest in our work! I just uploaded the codes. The data will be released soon.

Thank you for your great work, testing the code, and the calibration speed is really fast. Hope to adapt to scanning LiDAR and look forward to convenient data acquisition methods

**Comment by llihku** [comment]
> > Thanks for your interest in our work! I just uploaded the codes. The data will be released soon.
> > Hello, thank you very much for your open source code. I just looked at the data. Does this only support solid-state LiDAR

The method is not only designed for solid-state LiDARs. It is suitable for traditional mechanically spinning LiDARs as well. The key of this work is to enforce LiDAR plane constraints to 3D visual points. We can determine whether a visual point is associated with a LiDAR plane by searching for its nearest neighbor point cloud and calculating the corresponding eigen values (see the **void Calib::joint_calib()** function). This does not depend too much on the LiDAR scanning pattern. We will upload our paper soon. The paper details our method.

**Comment by llihku** [comment]
> > Thanks for your interest in our work! I just uploaded the codes. The data will be released soon.
> 
> Thank you for your great work, testing the code, and the calibration speed is really fast. Hope to adapt to scanning LiDAR and look forward to convenient data acquisition methods

Generally speaking, the codes can be used for scanning LiDAR without laborious parameter tuning. The corresponding parameters values (**nearest_neighbor_num**: 50; **eigen_ratio_thre**: 9.0; **point_to_plane_dist_thre**: 0.05) are robust. The only parameter you might need to change is the weighting factor **alpha_sqrt**. The suggested data acquisition method will be provided soon.

**Comment by af-doom** [comment]
> acquisition

Thank you very much for your reply. Looking forward to your paper.Regarding the 16 line LiDAR data acquisition method: moving the device to multiple poses, recording images, and current single frame point cloud PCD.

**Comment by af-doom** [comment]
> > > Thanks for your interest in our work! I just uploaded the codes. The data will be released soon.
> > 
> > 
> > Thank you for your great work, testing the code, and the calibration speed is really fast. Hope to adapt to scanning LiDAR and look forward to convenient data acquisition methods
> 
> Generally speaking, the codes can be used for scanning LiDAR without laborious parameter tuning. The corresponding parameters values (**nearest_neighbor_num**: 50; **eigen_ratio_thre**: 9.0; **point_to_plane_dist_thre**: 0.05) are robust. The only parameter you might need to change is the weighting factor **alpha_sqrt**. The suggested data acquisition method will be provided soon.

Thank you very much for your reply. Looking forward to your paper.Regarding the 16 line LiDAR data acquisition method: moving the device to multiple poses, recording images, and current single frame point cloud PCD.

**Comment by af-doom** [comment]
> Generally speaking, the codes can be used for scanning LiDAR without laborious parameter tuning. The corresponding parameters values (**nearest_neighbor_num**: 50; **eigen_ratio_thre**: 9.0; **point_to_plane_dist_thre**: 0.05) are robust. The only parameter you might need to change is the weighting factor **alpha_sqrt**. The suggested data acquisition method will be provided soon.

Great work, it's really convenient not to need to adjust too many parameters. Looking forward to 16 line laser calibration examples.

**Comment by af-doom** [comment]
> > > Thanks for your interest in our work! I just uploaded the codes. The data will be released soon.
> > 
> > 
> > Thank you for your great work, testing the code, and the calibration speed is really fast. Hope to adapt to scanning LiDAR and look forward to convenient data acquisition methods
> 
> Generally speaking, the codes can be used for scanning LiDAR without laborious parameter tuning. The corresponding parameters values (**nearest_neighbor_num**: 50; **eigen_ratio_thre**: 9.0; **point_to_plane_dist_thre**: 0.05) are robust. The only parameter you might need to change is the weighting factor **alpha_sqrt**. The suggested data acquisition method will be provided soon.

I found that the introduction has been updated, You are so effective, waiting for usage
