### ISSUE TITLE
About the selection of calibration scene

### ISSUE THREAD

**Issue by gjf281** [hku-mars/joint-lidar-camera-calib#11]
![image](https://github.com/hku-mars/joint-lidar-camera-calib/assets/7101742/6e258d1b-2852-4e35-924a-f49dfa230340)

In section 4.1,  it says "The ideal calibration scene usually consists of multiple textured planes",  but i think the floor plane in the above image  is not  textured plane. Am I right?

**Comment by llihku** [comment]
Hi. Actually there are abundant textures on this floor. You can visualize the Structure-from-Motion result of this scene (https://connecthkuhk-my.sharepoint.com/:f:/r/personal/llihku_connect_hku_hk/Documents/hku_campus/data2/[result](https://connecthkuhk-my.sharepoint.com/:f:/r/personal/llihku_connect_hku_hk/Documents/hku_campus/data2/result?csf=1&web=1&e=6fzqCW)?csf=1&web=1&e=6fzqCW) by PCL viewer or CloudCompare. There are many 3D points triangulated from the flooor plane.
