### ISSUE TITLE
相机初始化部分的问题

### ISSUE THREAD

**Issue by pedestrain123** [hku-mars/joint-lidar-camera-calib#13]
您好，非常感谢您工作的贡献。关于相机初始化部分sfm生成的三个txt文件（cameras.txt，images.txt，points3D.txt）是通过colmap这个开源软件生成的，请问有开源代码可以通过命令行执行命令的方式生成吗？不需要通过UI界面

**Comment by llihku** [comment]
https://colmap.github.io/cli.html#commands
