### ISSUE TITLE
请教手持设备的时间同步

### ISSUE THREAD

**Issue by NeoZng** [hku-mars/joint-lidar-camera-calib#14]
请问论文图中使用的相机是海康机器人的GigE网口相机吗？是否支持作为从机进行PTP呢？
![image](https://github.com/user-attachments/assets/7bd77137-517c-49cf-88b4-66475127aba9)

**Comment by llihku** [comment]
使用的是USB相机，不支持PTP。(但是海康有部分型号的相机支持PTP)
