### ISSUE TITLE
LiDAR Pose estimation for a 32 beam mechanical LiDAR seems Incorrect

### ISSUE THREAD

**Issue by bharadwajakshay** [hku-mars/joint-lidar-camera-calib#15]
Hi,
Thank you for the work. While using the work with a 32 Beam  mechanical lidar, the lidar pose estimation seems incorrect, as inspecting the **_"clouds_all.pcd"_** file show improper registration. Please check the image below. 
![image](https://github.com/user-attachments/assets/d85d744c-9b96-489a-a01d-ecd5f70b624c)

Any idea why this is happening? Can you please point me in the right direction to fix this issue. 

Thanks

**Comment by llihku** [comment]
Hi. Based on your image, the motion (especially the rotation) of the sensor suite is more aggressive than expected. Try to make gentle motion (e.g. 3~5 degrees of rotation and 5~10 cm of translation) between consecutive frames.
