### ISSUE TITLE
Arguments in config.yaml

### ISSUE THREAD

**Issue by MesssitO** [hku-mars/joint-lidar-camera-calib#16]
Hi,
Thank you for the work. We followed the steps of Chapter 4 in README, and when we tried to do the last step joint optimization, we met some problems:
1. We found in one of the issues that nearest_neighbor_num, eigen_ratio_thre, point_to_plane_dist_thre are robust, and they don't need to be changed. But for alpha_sqrt, how do I change its value?
![QQ20241017-160159](https://github.com/user-attachments/assets/cd44bdb9-7b3e-4c0f-9c22-80a651a1c456)

2.  For the initial guess of the extrinsic parameters, we wanna use your hand_eye_calib.cpp, but don't know that how can get those poses just like your sample data? Were they generated in previous steps?
![QQ20241017-161754](https://github.com/user-attachments/assets/4509118d-eb02-4cc7-b58b-59fb73b179a8)

Can you please point me in the right direction to fix those issues?
Thanks

**Comment by llihku** [comment]
Hi.
1. The parameter alpha_sqrt (square root of alpha in the paper) represents your confidence level in the LiDAR plane parameters. Generally speaking, the more accurate the LiDAR measurements, the larger the parameter. In practice, I found [0.1, 10] to be a suitable domain for alpha_sqrt ([0.01, 100] for alpha). You may need to tune this parameter within the domain.
2. Admittedly I only provide sample code for LiDAR pose estimation. For camera pose estimation, you can use COLMAP if you don't know the intrinsic parameters, or use COLMAP/ORB-SLAM etc. if intrinsic parameters are known.
