### ISSUE TITLE
In the paper, it is mentioned that solid-state LiDAR is stationary for 3 seconds to collect data on a pose, so how should 16-line LiDAR collect data on a pose

### ISSUE THREAD

**Issue by af-doom** [hku-mars/joint-lidar-camera-calib#2]

**Comment by llihku** [comment]
For mechanically spininig LiDAR, a scan is enough for each pose.

**Comment by af-doom** [comment]
> For mechanically spininig LiDAR, a scan is enough for each pose.
Thank you for your reply. Do we need to generate "lidar_poses_BA. txt" and "points3D. txt" through BA and SFM? It seems that there is currently no code available for these parts

**Comment by llihku** [comment]
> > For mechanically spininig LiDAR, a scan is enough for each pose.
> > Thank you for your reply. Do we need to generate "lidar_poses_BA. txt" and "points3D. txt" through BA and SFM? It seems that there is currently no code available for these parts

Indeed, currently there are no codes for these parts. The approach for generating these files will be detailed in the following days.

**Comment by llihku** [comment]
The approaches for generating "lidar_poses_BA. txt" and "points3D. txt" have been updated.

**Comment by af-doom** [comment]
> The approaches for generating "lidar_poses_BA. txt" and "points3D. txt" have been updated.

Thank you for your update
