### ISSUE TITLE
作者您好，非常感谢您能开源此项工作的代码，对于代码中的内容有几个问题想请教一下，感谢您的回答。

### ISSUE THREAD

**Issue by Tony-TF** [hku-mars/joint-lidar-camera-calib#3]
1.对于32线旋转机械式激光雷达，采集数据是否是连续采集，还是挪动一下采集一帧数据直到满足6～8帧数据。如果是连续采集数据的话，相机类型有什么限制吗？
2.在采集数据详细说明中提到需要在xy轴平面和航向角上进行小范围的移动，以免退化。是否方向一定要如此，可以在xz轴平面上和俯仰角进行小范围移动呢？
3.使用COLMAP获取相机的姿态能补充说明下嘛？

期待/感谢您回答

**Comment by llihku** [comment]
感谢你对这个工作的关注！
1. 推荐挪动一下采集一帧数据直到满足6～8帧数据，但如果能保证处理好连续采集数据可能出现的问题(比如数据不同步、点云运动畸变)，那么连续采集也是可以的。相机类型无限制，但暂时没有给鱼眼/全景相机做过测试，不确定是否有同样高的精度。
2. 可以。
3. 近期会尽快上传一个视频讲解如何用COLMAP进行自标定(同时涵盖了相机姿态估计)。

**Comment by Tony-TF** [comment]
感谢您的回答
