### ISSUE TITLE
Calibration Performance - İmplementation on KITTI Dataset

### ISSUE THREAD

**Issue by calibratorterminator55** [hku-mars/joint-lidar-camera-calib#4]
Hello,

I just wanted to say thanks for the fantastic work you've been doing. It's been a real pleasure to go through.
I've got a bunch of questions about the joint lidar calibration with Velodyne-HDL-64:

- Would it be possible for you to provide the source code you utilized in experiments with the KITTI Dataset? I believe I can learn a lot from this implementation.

- I have observed that when I changed the config/config.yaml => camera_coeffs nothing is changing. In the code, it doesn't affect anything. Why we are writing the camera_coeffs ( intrinsic parameters)? Also, I know the intrinsic parameter initially and I want to accept it as ground truth. How can I do that?

- When I tried to do the calibration on my own using a custom dataset, I ran into some issues. The calibration results were quite different from what's suggested in the paper.
 For example, my ground truth translation was [0.303, 0.596, -1.890], but I ended up with [3.16, 0.642, -4.33]. Also, the ground truth rotation matrix in Euler radians was [-1.572, 0.032, -0.787], but my results were [-1.4831931, 0.1939253, -1.2888357]. (I converted the rotation matrix to Euler angles for better understanding.)

### Data Collection:
- Initially, I thought there might be an issue with my data collection. So, I tried various scenes with different camera-lidar translations and rotations, making sure to adhere to the "at least three planes constraint." What should I focus on during data collection to improve calibration results?
- I investigated that forward motion is problematic with COLMAP's reconstruction. To avoid this, I tried to minimize forward motion in my scenes, but it didn't seem to help. 
Reference: https://github.com/colmap/colmap/issues/1490

- I experimented with using more than 8 images to see if it would improve reconstruction quality. However, it didn't seem to affect the self-calibration process. Is it better or worse to use more images for self-calibration?

If you have any thoughts or ideas on these issues, I'd really appreciate your input.

Thanks again! I'll be waiting for your response.

**Comment by llihku** [comment]
Thanks for your interest in my work!
1. Sure. I can send you the demo code for running our algorithm on the KITTI dataset.
2. Indeed, it does not change anything. The camera_coeffs in config/config.yaml only serves as the reference (for instance, intrinsic parameters calibrated by standard chessboard-based methods), to indicate the accuracy of our method. If you are pretty confident in your intrinsic parameters and do not want to optimize them, set keep_intrinsic_fixed to true in config/config.yaml.
3. You can send the data which produce exactly the same result to my email (llihku@connect.hku.hk). I will take a look.
4. I will give my answer after seeing your collected data.
5. Several months ago I also encountered this problem on KITTI dataset. However, the solution is straightforward. Simply change two parameters in COLMAP and everything will be fine. I will detail the solution soon.
6. Frankly speaking, I do not know either. While intuitively the more data, the better, I have not conducted experiments to verify this.

**Comment by llihku** [comment]
![Screenshot from 2023-10-06 13-44-03](https://github.com/hku-mars/joint-lidar-camera-calib/assets/87013040/866e8246-60b7-4f73-b558-a886c029c0e2)

Increase init_max_forward_motion to 1.0 and decrease init_min_tri_angle to 5.0.
This should help with your case.

**Comment by deliangye** [comment]
could you please send the demo code for running your algorithm on the KITTI dataset if possible? I am interested in how you extract the 8 image-lidar scan pairs to run this calibration. Thanks a lot!

**Comment by llihku** [comment]
Hi,
These are the code and configuration files for KITTI odometry dataset sequence 00. I just noticed that my OneDrive account had expired because of my graduation, so the corresponding data was lost. When running my algorithm on KITTI, 8 scan pairs are generally not enough because the KITTI data provide insufficient constraints on Z-axis. I used 50-100 consecutive scans of each sequence to produce the results reported in my paper. Hope this email helps.

Best,
Liang Li
________________________________
