### ISSUE TITLE
Unable to open config.yaml

### ISSUE THREAD

**Issue by gitouni** [hku-mars/joint-lidar-camera-calib#5]
Thanks for your amazing work. However, I met errors when run the command
`roslaunch joint_lidar_camera_calib calib.launch`.
```
process[calib-2]: started with pid [85717]
[ERROR] [1699574319.919059511]: Unable to open xxx/joint-lidar-camera-calib/data_/00/config/config.yaml
[ERROR] [1699574319.919465603]: Check configuration file.
```
The `config/config.yaml` file you show in the directory tree is not given in this project. As it provides default parameters, can you share this file in the github? Really appreciate your reply.

**Comment by llihku** [comment]
Hi. The config file is provided in Section 3 Sample Data.
