### ISSUE TITLE
Input point cloud has no data

### ISSUE THREAD

**Issue by hecperleo** [hku-mars/joint-lidar-camera-calib#6]
Hello, first, thanks for sharing your work!

I tried with the provided example data and your software worked without issues, so I guess that there is no installation problems. Then I tried with my own data, I was able to run the COLMAP software, and the commands of section `LiDAR Pose Estimation` without errors. However, I am receiving the following output running the last command `roslaunch joint_lidar_camera_calib calib.launch`:

```
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!
  ```

[Here is my data](https://drive.google.com/file/d/1cLwu-T4zapwR2-drRiSleHRV3db4E-W0/view?usp=drive_link) with the folder structure, there should be something that I am missing. I am obtaining the data by recording a rosbag and then converting it into a PCD. I am using a [Blickfeld Cube 1](https://www.blickfeld.com/lidar-sensor-products/cube-1/) sensor, is the point cloud dense enough?

**Comment by llihku** [comment]
Hi, I checked your data. 
1. The reason why you got the error is that your file points3D.txt in the SfM folder is empty. Please check whether your structure-from-motion in COLMAP succeeds.
2. The point cloud is dense enough.
3. I noticed another issue, although it has nothing to do with the error. The default parameters in LiDAR Pose Estimation does not work for your data. You can visualize the cloud_all.pcd in CloudCompare. It is rather cluttered, meaning point cloud registration fails already. Parameter tuning is needed.
