### ISSUE TITLE
  calib.refine_scale_ext() This step reports an error

### ISSUE THREAD

**Issue by af-doom** [hku-mars/joint-lidar-camera-calib#7]
INFO] [1705077562.793562945]: SfM point cloud saved as /home/wyw/ROS1_PROJECT/2023/camera_lidar_new/joint_camera_lidar/data/result/SfM_cloud_init.pcd
[ INFO] [1705077563.347440279]: LiDAR point clouds saved as /home/wyw/ROS1_PROJECT/2023/camera_lidar_new/joint_camera_lidar/data/result/LiDAR_cloud.pcd

[ INFO] [1705077563.359045062]: Initial visual scale recovered. Value: 0.134602
calib: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:425: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
[calib-1] process has died [pid 1377675, exit code -6, cmd /home/wyw/ROS1_PROJECT/2023/camera_lidar_new/joint_camera_lidar/devel/lib/joint_lidar_camera_calib/calib __name:=calib __log:=/home/wyw/.ros/log/06631870-b0fe-11ee-8f7d-4d0d94364953/calib-1.log].
log file: /home/wyw/.ros/log/06631870-b0fe-11ee-8f7d-4d0d94364953/calib-1*.log

**Comment by af-doom** [comment]
> INFO] [1705077562.793562945]: SfM point cloud saved as /home/wyw/ROS1_PROJECT/2023/camera_lidar_new/joint_camera_lidar/data/result/SfM_cloud_init.pcd [ INFO] [1705077563.347440279]: LiDAR point clouds saved as /home/wyw/ROS1_PROJECT/2023/camera_lidar_new/joint_camera_lidar/data/result/LiDAR_cloud.pcd
> 
> [ INFO] [1705077563.359045062]: Initial visual scale recovered. Value: 0.134602 calib: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:425: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed. [calib-1] process has died [pid 1377675, exit code -6, cmd /home/wyw/ROS1_PROJECT/2023/camera_lidar_new/joint_camera_lidar/devel/lib/joint_lidar_camera_calib/calib __name:=calib __log:=/home/wyw/.ros/log/06631870-b0fe-11ee-8f7d-4d0d94364953/calib-1.log]. log file: /home/wyw/.ros/log/06631870-b0fe-11ee-8f7d-4d0d94364953/calib-1*.log

When I comment out (calib.refine_scale_ext();) no error is reported

**Comment by llihku** [comment]
This problem arises from the variable evalsMid in function Calib::calc_plane. In some extreme cases it exceeds the size of Eigen::Vector3d evalsReal. I have updated codes to deal with this problem.
