### ISSUE TITLE
How to use this calibration tool on an equirectangular camera model?

### ISSUE THREAD

**Issue by G4419** [hku-mars/joint-lidar-camera-calib#9]
Colmap does not support equirectangular models, how can I obtain SFM data? Also, does equirectangular not require camera intrinsics and distortion coefficients?

**Comment by G4419** [comment]
I used OpenMVG to get this Colmap-formatted data from the panorama image. Can this data be used?
https://1drv.ms/f/c/a0cedbea61e6c931/EtMSk-1YrjhMkZ3PE3YU35YBs53llaj2y6XZ97mVzt6NDA?e=vUmyNf

**Comment by G4419** [comment]
https://github.com/openMVG/Image_datasets/tree/main/360_dataset/360_Flat/images
And this is the data i used.

**Comment by llihku** [comment]
> I used OpenMVG to get this Colmap-formatted data from the panorama image. Can this data be used? https://1drv.ms/f/c/a0cedbea61e6c931/EtMSk-1YrjhMkZ3PE3YU35YBs53llaj2y6XZ97mVzt6NDA?e=vUmyNf

Sorry I cannot access your result by clicking this url. Is there any other way to share your result?

**Comment by G4419** [comment]
https://1drv.ms/f/c/a0cedbea61e6c931/EtMSk-1YrjhMkZ3PE3YU35YBJwU1-DY1ufAas1MNUPNawg
This should work.

**Comment by llihku** [comment]
> https://1drv.ms/f/c/a0cedbea61e6c931/EtMSk-1YrjhMkZ3PE3YU35YBJwU1-DY1ufAas1MNUPNawg This should work.

![微信图片_20240321202409](https://github.com/hku-mars/joint-lidar-camera-calib/assets/87013040/cd568ff2-9e82-4f15-b35b-e88ea82248c7)
Still. Is there any other way to share your result?(e.g. Google Drive, OneDrive, Baiduyunpan,...) What kind of data do you share? Are they a folder, a point cloud file, or a bin file?

**Comment by G4419** [comment]
This is a OneDrive link. I tried it on another device, and it can be opened. The link contains a file that has images, cameras, and points.txt

**Comment by G4419** [comment]
I don't understand why you can't open it. I uploaded it to Google Drive. Here is the link.https://drive.google.com/file/d/1Nx2Z6H2jiJ1HRuweYid590VXf7TpBnpq/view?usp=sharing

**Comment by G4419** [comment]
It converts spherical images to six cubic images. 
 https://github.com/openMVG/openMVG/issues/2089#issuecomment-1168286367

**Comment by llihku** [comment]
> It converts spherical images to six cubic images. [openMVG/openMVG#2089 (comment)](https://github.com/openMVG/openMVG/issues/2089#issuecomment-1168286367)

Have you already calibrated the intrinsic parameters of your panoramic camera before you use openMVG to do SfM?

**Comment by G4419** [comment]
Isn't the intrinsic parameter of the equidistant camera model typically just the width and height of the image?
